# Generated by Django 4.2.4 on 2023-09-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('listed_cn', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
